services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel

    web:
        image: nginx:alpine
        container_name: nginx_web
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

    node:
        image: node:18-alpine
        container_name: node_build
        working_dir: /var/www
        volumes:
            - .:/var/www
        tty: true
        ports:
            - "5173:5173" # Vite default port
        networks:
            - laravel

volumes:
    mysql_data:

networks:
    laravel:
        driver: bridge
