name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, bcmath, zip
          coverage: none

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install
          npm run build

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 64000
          script: |
            # Buat direktori jika belum ada
            mkdir -p /var/www/html/rpl2b-kelompok1
            cd /var/www/html/rpl2b-kelompok1

            # Clone atau pull repository
            if [ ! -d "signix_web" ]; then
              git clone https://github.com/${{ github.repository }}.git signix_web
              cd signix_web
            else
              cd signix_web
              git pull origin main
            fi

            # Install dependencies
            composer install --no-interaction --prefer-dist --optimize-autoloader
            npm install
            npm run build

            # Setup Laravel
            php artisan storage:link
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan migrate --force

            # Set permissions
            chmod -R 775 .
            chmod -R 777 storage bootstrap/cache
            chown -R www-data:www-data .

            # Restart services jika diperlukan
            sudo systemctl restart php8.1-fpm
            sudo systemctl restart nginx
